### ISSUE TITLE
Highlighting uses wrong source locations on Windows

### ISSUE THREAD

**Issue by archaeron** [david-christiansen/idris-code-highlighter#6]
![highlight_main](https://cloud.githubusercontent.com/assets/471043/9371239/6af17010-46d7-11e5-82e0-bd14bcaf55fd.PNG)

**Comment by david-christiansen** [comment]
Interesting, on my machine it looks like this:
![screenshot from 2015-08-19 16 07 12](https://cloud.githubusercontent.com/assets/115330/9371274/6a727a3a-468c-11e5-90f7-5f9b53be4ba4.png)

If I had to guess, it's that there's something related to newlines, as I believe you're on Windows. But any help diagnosing would be welcome!

**Comment by david-christiansen** [comment]
How does the TeX backend look?

**Comment by archaeron** [comment]
I can't test the TeX output because I haven't installed the needed environement, but I'll search for the error in the Html.

**Comment by david-christiansen** [comment]
Thanks!

**Comment by archaeron** [comment]
could you post your idh file in a gist and I'll post mine, to see if they at least are the same?

**Comment by david-christiansen** [comment]
Take a look at the function "highlight" in the Formats module. In particular, you might have good luck seeing how the splitting into lines works, using `Debug.Trace.trace`. I would suspect that it's a problem with newline definitions.

**Comment by archaeron** [comment]
here is my idh file: https://gist.github.com/archaeron/b491ff01dcf0c401c4bc

**Comment by david-christiansen** [comment]
https://gist.github.com/0e610ffbe018736d373c for mine

**Comment by david-christiansen** [comment]
Source locations seem to agree, so it's probably a newline handling bug in the highlighter

**Comment by david-christiansen** [comment]
Can now confirm that the TeX backend exhibits the same issue on @archaeron's machine: https://gist.github.com/archaeron/55caca5b24c13d556bce

**Comment by archaeron** [comment]
well, doesn't matter what I do, I can't reporduce the error now. All seems to be well now.
Sorry for the inconvenience.

**Comment by david-christiansen** [comment]
Thanks for a good report! We can reopen if it happens again.
